table dim_issue_type
	column issue_type_key
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: issue_type_key
	column issue_type_name
		dataType: string
		summarizeBy: none
		sourceColumn: issue_type_name
	partition dim_issue_type = m
		mode: import
		source = ```
				let
					FilePath = #"DataFolder" & "dim_issue_type.csv",
					Source = Csv.Document(File.Contents(FilePath), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"issue_type_key", Int64.Type}, {"issue_type_name", type text}})
				in
					Typed
			```
