/// One row per received date.
table dim_date
	column date_key
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: date_key
	column date_received
		dataType: dateTime
		formatString: yyyy-MM-dd
		summarizeBy: none
		sourceColumn: date_received
	column calendar_year
		dataType: int64
		summarizeBy: none
		sourceColumn: calendar_year
	column calendar_month
		dataType: int64
		summarizeBy: none
		sourceColumn: calendar_month
	column calendar_day
		dataType: int64
		summarizeBy: none
		sourceColumn: calendar_day
	partition dim_date = m
		mode: import
		source = ```
				let
					FilePath = #"DataFolder" & "dim_date.csv",
					Source = Csv.Document(File.Contents(FilePath), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"date_key", Int64.Type}, {"date_received", type date}, {"calendar_year", Int64.Type}, {"calendar_month", Int64.Type}, {"calendar_day", Int64.Type}})
				in
					Typed
			```
