/// Party that submitted the RFI.
table dim_party
	column party_key
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: party_key
	column party_name
		dataType: string
		summarizeBy: none
		sourceColumn: party_name
	partition dim_party = m
		mode: import
		source = ```
				let
					FilePath = #"DataFolder" & "dim_party.csv",
					Source = Csv.Document(File.Contents(FilePath), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"party_key", Int64.Type}, {"party_name", type text}})
				in
					Typed
			```
